name: SureFire
favicon: null
layout_spectrum: 0.08102814271114767
typography_spectrum: 0.8680317525286227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5442885956726968
  lightness: 0.6253477199934423
  saturation: 0.9522920870222151
  rhythmicContrast: 0.8844079924747348
purpose: []
